"""add raw_text_original to documents

Revision ID: 213df290cac5
Revises: 2187b171bdc7
Create Date: 2026-01-10 16:31:02.696945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213df290cac5'
down_revision: Union[str, Sequence[str], None] = '2187b171bdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_text_original', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_text_original')
    # ### end Alembic commands ###
