"""add transaksional models

Revision ID: 42f9cb8d4479
Revises: 213df290cac5
Create Date: 2026-01-10 19:11:50.240366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42f9cb8d4479'
down_revision: Union[str, Sequence[str], None] = '213df290cac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_state',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('collected_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('bot_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('student_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('student_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('academic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_registrations_id'), 'student_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_student_registrations_registration_number'), 'student_registrations', ['registration_number'], unique=True)
    op.create_index(op.f('ix_student_registrations_status'), 'student_registrations', ['status'], unique=False)
    op.create_table('registration_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['student_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_documents_id'), 'registration_documents', ['id'], unique=False)
    op.create_index(op.f('ix_registration_documents_registration_id'), 'registration_documents', ['registration_id'], unique=False)
    op.create_table('registration_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['student_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_tracking_id'), 'registration_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_registration_tracking_registration_id'), 'registration_tracking', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_tracking_registration_id'), table_name='registration_tracking')
    op.drop_index(op.f('ix_registration_tracking_id'), table_name='registration_tracking')
    op.drop_table('registration_tracking')
    op.drop_index(op.f('ix_registration_documents_registration_id'), table_name='registration_documents')
    op.drop_index(op.f('ix_registration_documents_id'), table_name='registration_documents')
    op.drop_table('registration_documents')
    op.drop_index(op.f('ix_student_registrations_status'), table_name='student_registrations')
    op.drop_index(op.f('ix_student_registrations_registration_number'), table_name='student_registrations')
    op.drop_index(op.f('ix_student_registrations_id'), table_name='student_registrations')
    op.drop_table('student_registrations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('conversation_state')
    # ### end Alembic commands ###
