"""update panjang field

Revision ID: cde4757618a6
Revises: 42f9cb8d4479
Create Date: 2026-01-10 19:32:39.135788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde4757618a6'
down_revision: Union[str, Sequence[str], None] = '42f9cb8d4479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conv_session'), table_name='conversations')
    op.drop_index(op.f('idx_rd_reg_id'), table_name='registration_documents')
    op.drop_index(op.f('idx_rt_reg_id'), table_name='registration_tracking')
    op.alter_column('student_registrations', 'registration_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('idx_sr_reg_number'), table_name='student_registrations')
    op.drop_index(op.f('idx_sr_status'), table_name='student_registrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sr_status'), 'student_registrations', ['status'], unique=False)
    op.create_index(op.f('idx_sr_reg_number'), 'student_registrations', ['registration_number'], unique=False)
    op.alter_column('student_registrations', 'registration_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index(op.f('idx_rt_reg_id'), 'registration_tracking', ['registration_id'], unique=False)
    op.create_index(op.f('idx_rd_reg_id'), 'registration_documents', ['registration_id'], unique=False)
    op.create_index(op.f('idx_conv_session'), 'conversations', ['session_id'], unique=False)
    # ### end Alembic commands ###
